variables:
  BASE_IMAGE: ubuntu:18.04

stages:
  - pages
  - test-pages

.before-website-build: &before_website_build
  - apt update && apt install -yq python-pip
  - pip install -r requirements.txt

pages:
  stage: pages
  image: $BASE_IMAGE
  before_script: *before_website_build
  script:
  - make --directory ./website publish
  - mv website/output public
  artifacts:
    paths:
    - public
  only:
  - master

test-pages:
  stage: test-pages
  image: $BASE_IMAGE
  before_script: *before_website_build
  script:
  - make --directory ./website publish
  artifacts:
    paths:
    - website/output/
  except:
  - master
